<a href="https://colab.research.google.com/github/risitadas/machine-learning-in-python/blob/main/22.k-fold-cross-validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K Fold Cross Validation :

evaluating model performance

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(digits.data, digits.target,test_size=0.3)

Logistic Regression

In [4]:
lr = LogisticRegression(solver = 'liblinear', multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9537037037037037

SVM

In [5]:
svm = SVC(gamma = 'auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.337037037037037

Random Forest

In [6]:
rf = RandomForestClassifier(n_estimators = 40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9740740740740741

KFold cross validation

In [9]:
# example
from sklearn.model_selection import KFold
kf = KFold(n_splits = 3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


using KFold for our digits dataset 

In [13]:
def get_score(model, X_train, X_test, y_train, y_test):
  model.fit(X_train, y_train)
  return model.score(X_test, y_test)

In [15]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
  X_train, X_test, y_train, y_test = digits.data[train_index] , digits.data[test_index], \
                                     digits.target[train_index] , digits.target[test_index]


  scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
  scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
  scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))                                  

In [16]:
scores_logistic

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [17]:
scores_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [18]:
scores_rf

[0.9298831385642737, 0.9499165275459098, 0.9181969949916527]

cross_val_score function

In [19]:
from sklearn.model_selection import cross_val_score

Logistic Regression model performance using cross_val_score

In [20]:
cross_val_score(LogisticRegression(solver = 'liblinear', multi_class = 'ovr'), digits.data, digits.target, cv = 3)

array([0.89482471, 0.95325543, 0.90984975])

svm model performance using cross_val_score

In [21]:
cross_val_score(SVC(gamma = 'auto'), digits.data, digits.target, cv = 3)

array([0.38063439, 0.41068447, 0.51252087])

random forest performance using cross_val_score

In [23]:
cross_val_score(RandomForestClassifier(n_estimators = 40), digits.data, digits.target, cv = 3)

array([0.94824708, 0.94824708, 0.91819699])

parameter tunning using K Fold cross validation

In [26]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8659124767225327

In [24]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9365394165114834

In [25]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)


0.9426784605834884

In [27]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9454624456859093