<a href="https://colab.research.google.com/github/risitadas/machine-learning-in-python/blob/main/23.k-fold-cross-validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

K Fold Cross Validation :

using the iris flower dataset from sklearn library and using cross_val_score against following models to measure the performance of each, in the end figure out the model with best performance,

1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest

In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [2]:
iris = load_iris()

Logistic Regression

In [12]:
l_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
l_scores

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [13]:
np.average(l_scores)

0.9733333333333334

Decision Tree

In [5]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores

array([0.96666667, 0.96666667, 0.9       , 1.        , 1.        ])

In [6]:
np.average(d_scores)

0.9666666666666668

Support Vector Machine(SVM)

In [8]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [9]:
np.average(s_scores)

0.9666666666666666

Random Forest

In [10]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators = 40),iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.93333333, 0.9       , 1.        ])

In [11]:
np.average(r_scores)

0.9533333333333334

best score is from Logistic Regression : 0.9733333333333334