<a href="https://colab.research.google.com/github/risitadas/machine-learning-in-python/blob/main/3_linear_regression_multiple_variable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

linear regression multiple variables : 

predicting home price in monroe, new jersey (USA)


In [21]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt

In [22]:
df = pd.read_csv('https://raw.githubusercontent.com/risitadas/machine-learning-in-python/main/homeprices-multiple-csv.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

data preprocessing : filling NA values with median value of a column

In [23]:
df.bedrooms.median()

4.0

In [24]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [25]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price', axis = 'columns'), df.price)

LinearRegression()

In [26]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [27]:
reg.intercept_

221323.00186540396

finding the price of home with 3000 sqr ft area, and 3 bedrooms and 40 year old

In [28]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([498408.25158031])

general equation : 

y = m1*x1 + m2*x2 + m3*x3 + b

home equation : 

price = m1 * area + m2 * bedrooms + m3 * age + b

where, price is dependent variable,
       area, bedrooms and age are independent variables(features),
       m1, m2, m3 are the coefficients


In [29]:
112.06244194 * 3000 + 23388.88007794 * 3 + -3231.71790863 * 40 + 221323.00186540396

498408.251574024

finding price of home with 2500 sqr ft area, 4 bedrooms, 5 year old

In [30]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([578876.03748933])