<a href="https://colab.research.google.com/github/risitadas/machine-learning-in-python/blob/main/7.save-load-trained-model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Save and Load Trained Model Using 
1. Pickle 
2. sklearn Joblib 

In [29]:
# importing necessary libraries
import pandas as pd
import numpy as np
from sklearn import linear_model

In [30]:
df = pd.read_csv('https://raw.githubusercontent.com/risitadas/machine-learning-in-python/main/homeprices-csv.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [31]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [32]:
model.coef_

array([135.78767123])

In [33]:
model.intercept_

180616.43835616432

In [34]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

1. save model to a file using python pickle 

In [35]:
import pickle

In [36]:
with open('model_pickle','wb') as f:
  pickle.dump(model,f)

load saved model

In [37]:
with open('model_pickle', 'rb') as f:
  mp = pickle.load(f)

In [38]:
mp.coef_

array([135.78767123])

In [39]:
mp.intercept_

180616.43835616432

In [40]:
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

2. save trained model using sklearn joblib

In [41]:
import joblib

In [42]:
joblib.dump(model, 'model_joblib')

['model_joblib']

load saved model

In [43]:
mj = joblib.load('model_joblib')

In [44]:
mj.coef_

array([135.78767123])

In [45]:
mj.intercept_

180616.43835616432

In [46]:
mj.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])